### ISSUE TITLE
Add slide to open menu

### ISSUE THREAD

**Issue by IronTony** [react-native-community/react-native-elements#115]

**Comment by dabit3** [comment]
@IronTony , can you give a little more info here? Thanks!

**Comment by Monte9** [comment]
@dabit3 As far as I can tell, you have implemented your own SideMenu with Animation right? I have used react-native-side-menu and I really like it. It does have slide to open menu as well. Maybe something similar needs to be implemented here. 
For reference, this is the repo I am talking about: https://github.com/react-native-community/react-native-side-menu

**Comment by dabit3** [comment]
@Monte9 I like that implementation better tbh. We can either pull this component out completely, or we can replace it with [react-native-side-menu](https://github.com/react-native-community/react-native-side-menu) like I did with the react-native-tab-navigation.

**Comment by Monte9** [comment]
@dabit3 I would still like to have it part of react-native-elements so that folks dont have to worry about importing react-native-side-menu separately. So I like the second idea better.. of replacing it with react-native-side-menu. 

Seems like a fun little project. Keep an eye out for a PR in the next few days.

**Comment by Monte9** [comment]
@dabit3 this was waaay easier than I thought. lol 
React Native Elements now uses [react-native-side-menu](https://github.com/react-native-community/react-native-side-menu). I really like this as we don't have to worry about any issues related to this component and can direct users to the repo directly. This way we can focus on the our custom elements and improve on them.

**Comment by Monte9** [comment]
Also @dabit3, there is not PR are all the changes are going into #v

**Comment by IronTony** [comment]
I had problem with that component, as you can see in the question I had written on their git: https://github.com/react-native-community/react-native-side-menu/issues/245
Instead using your implementation everything worked well and fast in 5 minutes.

**Comment by Monte9** [comment]
Hi @IronTony. Fair point. As @dabit3 and I discussed above, we thought it better to use the side-menu component as it's easier to maintain. Although I understand the issue you raised with not being able to dismiss the sidemenu when clicking on an item. 

Here's a couple pointers to resolve this issue:
1. use a prop `onContentPress` to handle this. Look at how it's implemented here: https://github.com/react-native-community/react-native-side-menu/tree/feature/truly-props-driven
2. Move the `isOpen` prop to a redux state instead of the component state. This way you dispatch an action to show another view and then close the drawer from there. 

Hope this helps. Feel free to submit a PR is you get something going.
