### ISSUE TITLE
ButtonGroup is broken

### ISSUE THREAD

**Issue by pewh** [react-native-community/react-native-elements#139]
Tested on latest version 0.9.0. I copy-paste from `ButtonGroup`'s example, both `Using string` and `Using component` are only show gray-line.

![screenshot_2017-01-05_11-19-00](https://cloud.githubusercontent.com/assets/881358/21668890/c9b15e50-d338-11e6-8d3b-d47eb2870d41.png)

**Comment by zibs** [comment]
2 cents: I found a similar issue the other day, but wasn't sure if I was the one messing things up myself since I was trying to use the button group within an absolutely positioned view. I was able to get the button group working (delicately) by messing around quite a bit with it's style - like height, flex etc. Might be worth trying to double check the context you are trying to use the button group in.  

However, I still think this might just be a bug, since I also noticed I was having trouble using it elsewhere as well..

**Comment by Monte9** [comment]
@pewh @zibs I'll look into it today. Thanks for bringing it up.

**Comment by Monte9** [comment]
@pewh Ok, here are two ways to use the ButtonGroup:
1. Embed the `ButtonGroup` in a `View` with a fixed height
2. Embed the `ButtonGroup` in a ScrollView (don't need to explicitly define the height)

Imo, this is not a bug as the `View` requires you to explicitly give it a height as it cannot inherit this from it's child component. Hence depending on your use case (View/ScrollView) you will need to give it a height.

With that being said, the documentation certainly needs to be updated to make this more clear. Will updated the documentation shortly. 

/cc @zibs

**Comment by KostasKostogloy** [comment]
I believe that this should be considered a bug. The components are meant to be autonomous pieces of UI. If there is a need for the button group to be wrapped inside a view, this should be handled inside the component (maybe pass it a height parameter and have a sensible default).

**Comment by KostasKostogloy** [comment]
@pewh @Monte9  I just realized there's an easier way. Pass the height on the `containerStyle` prop of the ButtonGroup

**Comment by Monte9** [comment]
@KostasKostogloy I'll add this to the readme. Thanks.
