### ISSUE TITLE
Prevent ListItem subtitle linebreak?

### ISSUE THREAD

**Issue by bexoss** [react-native-community/react-native-elements#238]
Hello, How to subtitle to set no-wrap in CSS like?

I want to fix subtitle to one line whether it is long or short. 

```
<ListItem
    subtitle = { 'long long long ................. long long long..............' }
    subtitleStyle = {{ whiteSpace: 'no-wrap' }} 
/>
```

How to do it properly? I think there is no style key 'whiteSpace' in RN.

**Comment by binoy14** [comment]
@bexoss Do you mean you want to do something like ellipsis if it is longer subtitle? http://codepen.io/chriscoyier/full/gvFGI/

**Comment by binoy14** [comment]
Closing this due to no response. @bexoss Feel free to open it if you are still having an issue

**Comment by xstable** [comment]
I have the same issue... if try to set the ListItem to 3 lines. Headline, and two sublines.
First line of subline should never reach into third line (but it does).

See Image here... third line is ok (distance have to be there - everytime!):
![listitem](https://user-images.githubusercontent.com/1778068/30437635-616556f0-996f-11e7-8a1a-dabb71e8960c.jpg)

But in first both entries you see, that the line as a break and end up with '...'.
That would be ok, if it only display one line instead of reaching into the second one.
