### ISSUE TITLE
Why is `react-native-vector-icons` listed in peerDependencies?

### ISSUE THREAD

**Issue by lsps9150414** [react-native-community/react-native-elements#91]
Why not list `react-native-vector-icons` as `dependencies`?

**Comment by dabit3** [comment]
It should be listed as a peer dependency because it must be installed before being able to use the library. Have you had any issues getting it up and running?

**Comment by dabit3** [comment]
Oh, just realized you said `peerDependencies` vs `dependencies`. Mainly because we did at first have it as a dependency and had a lot of people submitting issues because they could not get the vector icons installed, and had nothing to do with RN Elements, so we figured we'd let people get the icons installed themselves, which has led to less issues on our end.
